"""
Export API
==========
POST /export/chat  — export a chat conversation as a branded PDF report.
"""

import io
from datetime import datetime
from fastapi import APIRouter
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
)
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT

router = APIRouter(prefix="/export", tags=["export"])

W, H = A4
INDIGO = colors.HexColor("#4F46E5")
TEAL   = colors.HexColor("#0EA5E9")
DARK   = colors.HexColor("#0A0A0F")
GRAY   = colors.HexColor("#6B6B8A")
GREEN  = colors.HexColor("#10B981")
BG     = colors.HexColor("#F1F0FF")


class ChatMessage(BaseModel):
    role: str        # "user" | "ai"
    content: str
    citations: list[dict] = []


class ExportRequest(BaseModel):
    company_name: str = "Financial Document"
    messages: list[ChatMessage]


def _build_styles():
    styles = getSampleStyleSheet()
    base = dict(fontName="Helvetica", fontSize=10, leading=14)
    return {
        "title":     ParagraphStyle("title",     fontName="Helvetica-Bold", fontSize=20, textColor=INDIGO, spaceAfter=4),
        "subtitle":  ParagraphStyle("subtitle",  fontName="Helvetica",      fontSize=11, textColor=GRAY,   spaceAfter=12),
        "q_label":   ParagraphStyle("q_label",   fontName="Helvetica-Bold", fontSize=9,  textColor=INDIGO, spaceBefore=14, spaceAfter=2),
        "q_text":    ParagraphStyle("q_text",    fontName="Helvetica",      fontSize=11, textColor=DARK,   spaceAfter=6,  leading=16),
        "a_label":   ParagraphStyle("a_label",   fontName="Helvetica-Bold", fontSize=9,  textColor=TEAL,   spaceBefore=6, spaceAfter=2),
        "a_text":    ParagraphStyle("a_text",    fontName="Helvetica",      fontSize=10, textColor=DARK,   spaceAfter=4,  leading=15),
        "cite":      ParagraphStyle("cite",      fontName="Helvetica-Oblique", fontSize=8, textColor=GRAY, spaceAfter=2),
        "footer":    ParagraphStyle("footer",    fontName="Helvetica",      fontSize=8,  textColor=GRAY,  alignment=TA_CENTER),
        "divider":   ParagraphStyle("divider",   fontName="Helvetica",      fontSize=6,  textColor=GRAY),
    }


@router.post("/chat")
async def export_chat(request: ExportRequest):
    """
    Convert chat messages to a branded AlphaDesk PDF report.
    Returns the PDF as a file download.
    """
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=20*mm, rightMargin=20*mm,
        topMargin=18*mm, bottomMargin=18*mm,
    )

    styles = _build_styles()
    story = []

    # ── Header ──────────────────────────────────────────────
    story.append(Paragraph("AlphaDesk", styles["title"]))
    story.append(Paragraph(
        f"Research Report &nbsp;·&nbsp; {request.company_name} &nbsp;·&nbsp; {datetime.now().strftime('%d %b %Y')}",
        styles["subtitle"]
    ))
    story.append(HRFlowable(width="100%", thickness=1.5, color=INDIGO, spaceAfter=12))

    # ── Messages ─────────────────────────────────────────────
    q_num = 0
    for msg in request.messages:
        if msg.role == "user":
            q_num += 1
            story.append(Paragraph(f"Q{q_num}", styles["q_label"]))
            story.append(Paragraph(_safe(msg.content), styles["q_text"]))

        elif msg.role == "ai":
            story.append(Paragraph("Answer", styles["a_label"]))
            # Split on newlines to preserve paragraphs
            for para in msg.content.split("\n"):
                para = para.strip()
                if para:
                    story.append(Paragraph(_safe(para), styles["a_text"]))

            # Citations
            if msg.citations:
                pages = sorted({c.get("page_number", "?") for c in msg.citations})
                page_str = ", ".join(f"p.{p}" for p in pages)
                story.append(Paragraph(f"Sources: {page_str}", styles["cite"]))

            story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#E2E1F0"), spaceAfter=6))

    # ── Footer ───────────────────────────────────────────────
    story.append(Spacer(1, 8*mm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=GRAY))
    story.append(Spacer(1, 3*mm))
    story.append(Paragraph(
        f"Generated by AlphaDesk &nbsp;·&nbsp; ai-powered financial research &nbsp;·&nbsp; {datetime.now().strftime('%d %b %Y %H:%M')}",
        styles["footer"]
    ))

    doc.build(story)
    buf.seek(0)

    filename = f"AlphaDesk_{request.company_name.replace(' ', '_')}_{datetime.now().strftime('%Y%m%d')}.pdf"

    return StreamingResponse(
        buf,
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


def _safe(text: str) -> str:
    """Escape special characters for ReportLab Paragraph."""
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
